hyperparameters:
  batch_size: 1024
  buffer_size: 10240
network_settings:
  hidden_units: 64
time_horizon: 64

# hyperparameters:
#   batch_size: 2048
#   buffer_size: 20480
# network_settings:
#   hidden_units: 128
# time_horizon: 128